apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-monitor
  labels:
    app: uptime-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-monitor
  template:
    metadata:
      labels:
        app: uptime-monitor
    spec:
      containers:
      - name: uptime-monitor
        image: uptime-monitor:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
