apiVersion: v1
kind: Service
metadata:
  name: uptime-service
  labels:
    app: uptime-monitor
    release: prometheus
spec:
  type: NodePort
  selector:
    app: uptime-monitor
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30001
